version: '3.8'
services:
  app:
    image: timponomarev/youtube-comments-app:latest
    ports:
      - '8101:8101'
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
